"""Central metadata registry for IMAGINE Streamlit navigation."""
from __future__ import annotations
from dataclasses import dataclass

@dataclass(frozen=True, slots=True)
class ModuleSpec:
    route: str
    label: str
    section: str
    module_path: str | None = None
    renderer_name: str = "render"
    implemented: bool = False

FALLBACK = "modules.enterprise_missing"
STRUCTURAL_WORKBENCH = "modules.structural.workspaces"
EUROCODE_SUITE = "modules.structural.eurocode_suite"
DESIGN_BASIS = "modules.structural.design_basis"

def _m(route,label,section,path=FALLBACK,renderer="render",implemented=True): return ModuleSpec(route,label,section,path,renderer,implemented)

MODULE_SPECS: tuple[ModuleSpec, ...] = (
 _m("Overview","Overview","PLATFORM","__builtin__","render_overview"), _m("System Health","System Health","PLATFORM","__builtin__","render_system_health"), _m("Project Files","Project Files","PLATFORM","modules.platform.file_center"),
 _m("Projects","Projects","PROJECTS","projects.projects.ui","render_projects"), _m("Approvals","Approvals","PROJECTS","projects.approvals.ui","render_approvals"), _m("Revisions","Revisions","PROJECTS","projects.revisions.ui","render_revisions"), _m("Workflows","Workflows","PROJECTS","projects.workflows.ui","render_workflows"), _m("Governance","Governance","PROJECTS","projects.governance.ui","render_governance"),
 _m("Architecture Assistant","Architecture Assistant","ARCHITECTURE","architecture.assistant.ui","render_architecture_assistant"), _m("Design Standards","Design Standards","ARCHITECTURE","architecture.standards.ui","render_design_standards"), _m("Architectural Design Handbook","Architectural Design Handbook","ARCHITECTURE","architecture.standards.architectural_handbook","render_architectural_handbook"), _m("Zoning","Zoning","ARCHITECTURE","architecture.zoning.ui","render_zoning"), _m("Site Planning","Site Planning","ARCHITECTURE","architecture.site_planning.ui","render_site_planning"), _m("Floor Planning","Floor Planning","ARCHITECTURE","architecture.floor_planning.ui","render_floor_planning"), _m("Room Programming","Room Programming","ARCHITECTURE","architecture.room_programming.ui","render_room_programming"), _m("Compliance","Compliance","ARCHITECTURE","architecture.compliance.ui","render_compliance"), _m("Generative Design","Generative Design","ARCHITECTURE","architecture.generative_design.ui","render_generative_design"),
 _m("Structural Engineering Dashboard","Structural Engineering Dashboard","STRUCTURAL","modules.structural.design_dashboard"), _m("Structural Design Basis","Structural Design Basis","STRUCTURAL",DESIGN_BASIS), _m("Structural Design Handbook","Structural Design Handbook","STRUCTURAL","modules.structural.handbook"), _m("Building Materials","Building Materials","STRUCTURAL","modules.structural.building_materials"), _m("Load Combinations","Load Combinations","STRUCTURAL","modules.structural.load_combinations"), _m("Wind Actions","Wind Actions","STRUCTURAL","modules.structural.wind_actions"), _m("Seismic Actions","Seismic Actions","STRUCTURAL","modules.structural.seismic_actions"), _m("RC Detailing","RC Detailing","STRUCTURAL","modules.structural.rc_detailing"), _m("Eurocode Suite","Eurocode Suite","STRUCTURAL",EUROCODE_SUITE),
 *(_m(f"EN 199{i}",f"EN 199{i}","STRUCTURAL",EUROCODE_SUITE) for i in range(10)),
 _m("Beam Design","Beam Design","STRUCTURAL","modules.structural.beam_design"), _m("Column Design","Column Design","STRUCTURAL","modules.structural.column_design"), _m("Slab Design","Slab Design","STRUCTURAL","modules.structural.slab_design"), _m("Foundation Design","Foundation Design","STRUCTURAL",STRUCTURAL_WORKBENCH), _m("Retaining Walls","Retaining Walls","STRUCTURAL","modules.structural.retaining_walls"), _m("Punching Shear","Punching Shear","STRUCTURAL",STRUCTURAL_WORKBENCH), _m("Steel Members","Steel Members","STRUCTURAL",STRUCTURAL_WORKBENCH), _m("Steel Connections","Steel Connections","STRUCTURAL",STRUCTURAL_WORKBENCH), _m("Section Shapes","Section Shapes","STRUCTURAL",STRUCTURAL_WORKBENCH), _m("Roof Design","Roof Design","STRUCTURAL","modules.structural.roof_design"), _m("Stairs Design","Stairs Design","STRUCTURAL","modules.structural.stairs_design"), _m("Openings Design","Openings Design","STRUCTURAL","modules.structural.openings_design"), _m("Railings & Balustrades","Railings & Balustrades","STRUCTURAL","modules.structural.railings_design"), _m("Structural Analysis","Structural Analysis","STRUCTURAL","modules.structural.structural_analysis"), _m("Finite Element Analysis","Finite Element Analysis","STRUCTURAL",STRUCTURAL_WORKBENCH),
 _m("BIM Dashboard","BIM Dashboard","BIM","modules.bim.dashboard"), _m("Buildings","Buildings","BIM","modules.bim.buildings"), _m("Storeys","Storeys","BIM","modules.bim.storeys"), _m("Spaces","Spaces","BIM","modules.bim.spaces"), _m("Elements","Elements","BIM","modules.bim.elements"), _m("Assemblies & Types","Assemblies & Types","BIM","modules.bim.assemblies"), _m("IFC","IFC","BIM","modules.bim.ifc_export"), _m("COBie","COBie","BIM","modules.bim.cobie"), _m("BIM Coordination","BIM Coordination","BIM","modules.bim.coordination"), _m("BIM Quantities","BIM Quantities","BIM","modules.bim.quantities"), _m("BIM → Costing / BOQ","BIM → Costing / BOQ","BIM","modules.bim.costing_handoff"), _m("BIM → Digital Twin","BIM → Digital Twin","BIM","modules.bim.digital_twin"),
 _m("Integrated MEP Analysis","Integrated MEP Analysis","MEP","modules.mep.analysis"), _m("HVAC","HVAC","MEP","modules.mep.hvac"), _m("Ventilation","Ventilation","MEP","modules.mep.analysis"), _m("Chilled Water","Chilled Water","MEP","modules.mep.analysis"), _m("Energy Simulation","Energy Simulation","MEP","modules.mep.energy_simulation"), _m("Electrical Load Analysis","Electrical Load Analysis","MEP","modules.mep.electrical"), _m("Water Supply","Water Supply","MEP","modules.mep.plumbing"), _m("Drainage","Drainage","MEP","modules.mep.plumbing"),
 _m("BOQ","BOQ","COSTING","modules.costing.boq"), _m("Quantity Takeoff","Quantity Takeoff","COSTING","modules.costing.boq"), _m("Procurement","Procurement","COSTING","modules.costing.procurement"), _m("Forex","Forex","COSTING","modules.costing.forex"), _m("Inflation / Escalation","Inflation / Escalation","COSTING","modules.costing.escalation"), _m("Risk Analysis","Risk Analysis","COSTING","modules.costing.risk_analysis"),
 _m("Planning","Planning","CONSTRUCTION","modules.construction.progress_tracking"), _m("Scheduling","Scheduling","CONSTRUCTION","modules.construction.progress_tracking"), _m("RFIs","RFIs","CONSTRUCTION","modules.construction.rfis"), _m("Submittals","Submittals","CONSTRUCTION","modules.construction.submittals"), _m("Snagging","Snagging","CONSTRUCTION","modules.construction.snagging"), _m("Site Diaries","Site Diaries","CONSTRUCTION","modules.construction.site_diary"),
 _m("Drawing Management","Drawing Management","DOCUMENTS","modules.documents.drawing_register"), _m("Drawings","Drawings","DOCUMENTS","modules.documents.drawing_register"), _m("Document Register","Document Register","DOCUMENTS","modules.documents.documents"), _m("Specifications","Specifications","DOCUMENTS","modules.documents.specifications"), _m("Contracts","Contracts","DOCUMENTS","modules.documents.documents"), _m("Version Control","Version Control","DOCUMENTS","modules.documents.revisions"), _m("Transmittals","Transmittals","DOCUMENTS","modules.documents.transmittals"),
 _m("IMAGINE Architect","IMAGINE Architect","AI"), _m("IMAGINE Engineer","IMAGINE Engineer","AI"), _m("IMAGINE MEP","IMAGINE MEP","AI"), _m("IMAGINE QS","IMAGINE QS","AI"), _m("IMAGINE PM","IMAGINE PM","AI"), _m("Dashboards","Dashboards","ANALYTICS","modules.dashboard.dashboard"), _m("KPIs","KPIs","ANALYTICS","modules.analytics.kpis"), _m("Portfolio","Portfolio","ANALYTICS","modules.analytics.portfolio"), _m("Forecasting","Forecasting","ANALYTICS","modules.analytics.forecasting"), _m("Reporting","Reporting","ANALYTICS","modules.analytics.reporting"),
 _m("Uganda","Uganda","REGIONAL"), _m("Kenya","Kenya","REGIONAL"), _m("Tanzania","Tanzania","REGIONAL"), _m("Rwanda","Rwanda","REGIONAL"), _m("South Sudan","South Sudan","REGIONAL"), _m("Codes","Codes","REGIONAL"), _m("Zoning Laws","Zoning Laws","REGIONAL"),
 _m("Microsoft","Microsoft","INTEGRATIONS"), _m("AutoCAD","AutoCAD","INTEGRATIONS"), _m("Revit","Revit","INTEGRATIONS"), _m("Archicad","Archicad","INTEGRATIONS"), _m("Tekla","Tekla","INTEGRATIONS"), _m("IfcOpenShell","IfcOpenShell","INTEGRATIONS"), _m("ArcGIS","ArcGIS","INTEGRATIONS"), _m("Azure","Azure","INTEGRATIONS"), _m("Mapbox","Mapbox","INTEGRATIONS"),
 _m("Assets","Assets","DIGITAL TWIN","modules.digital_twin.assets"), _m("Sensors","Sensors","DIGITAL TWIN","modules.digital_twin.sensors"), _m("Telemetry","Telemetry","DIGITAL TWIN","modules.digital_twin.telemetry"), _m("Energy","Energy","DIGITAL TWIN"), _m("Maintenance","Maintenance","DIGITAL TWIN","modules.digital_twin.maintenance"), _m("Predictive AI","Predictive AI","DIGITAL TWIN","modules.digital_twin.predictive_ai"),
)
MODULES_BY_ROUTE={s.route:s for s in MODULE_SPECS}

def validate_registry()->None:
 routes=[s.route for s in MODULE_SPECS]; duplicates=sorted({r for r in routes if routes.count(r)>1})
 if duplicates: raise RuntimeError(f"Duplicate module routes detected: {duplicates}")
 for spec in MODULE_SPECS:
  if not spec.route.strip() or not spec.label.strip() or not spec.section.strip(): raise RuntimeError(f"Invalid module specification: {spec!r}")
  if spec.implemented and not spec.module_path: raise RuntimeError(f"Implemented module has no module path: {spec.route}")
validate_registry()
__all__=["ModuleSpec","MODULE_SPECS","MODULES_BY_ROUTE","validate_registry"]