"""
IMAGINE
Generative Design Repository

Async SQLAlchemy repository for:

    GenerativeDesignRun
    DesignCandidateRecord

Transaction ownership belongs to the service layer.

Repository methods:
    - add
    - select
    - update
    - delete
    - flush

Repository methods DO NOT:
    - commit
    - rollback

This allows GenerativeDesignService to treat generation as one
atomic database transaction.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Sequence
from uuid import UUID

from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from architecture.generative_design.models import (
    DesignCandidateRecord,
    GenerativeDesignRun,
    GenerativeDesignRunStatus,
    DesignCandidateStatus,
)


class GenerativeDesignRepository:
    """
    Async persistence repository for generative design.

    The repository deliberately does not own the transaction.
    """

    def __init__(
        self,
        session: AsyncSession,
    ) -> None:
        self.session = session

    # ==================================================================
    # RUNS
    # ==================================================================

    async def create_run(
        self,
        *,
        project_id: UUID,
        name: str,
        constraints: dict[str, Any],
        status: GenerativeDesignRunStatus,
        candidate_count: int = 0,
        created_by: str | None = None,
    ) -> GenerativeDesignRun:
        """
        Create and flush a generative design run.

        The UUID primary key is generated by BaseModel.
        """

        run = GenerativeDesignRun(
            project_id=project_id,
            name=name,
            constraints=constraints,
            status=status,
            candidate_count=candidate_count,
            created_by=created_by,
        )

        self.session.add(run)

        await self.session.flush()

        return run

    async def get_run(
        self,
        run_id: UUID,
    ) -> GenerativeDesignRun | None:
        """
        Retrieve a run by UUID.
        """

        statement = (
            select(GenerativeDesignRun)
            .where(
                GenerativeDesignRun.id == run_id
            )
        )

        result = await self.session.execute(
            statement
        )

        return result.scalar_one_or_none()

    async def get_run_with_candidates(
        self,
        run_id: UUID,
    ) -> GenerativeDesignRun | None:
        """
        Retrieve a run and its candidates.

        The relationship configured on GenerativeDesignRun is used
        explicitly to avoid asynchronous lazy-loading problems.
        """

        statement = (
            select(GenerativeDesignRun)
            .where(
                GenerativeDesignRun.id == run_id
            )
        )

        result = await self.session.execute(
            statement
        )

        run = result.scalar_one_or_none()

        if run is None:
            return None

        # The relationship is expected to be configured on the
        # GenerativeDesignRun model as `candidates`.
        await self.session.refresh(
            run,
            attribute_names=["candidates"],
        )

        return run

    async def list_runs(
        self,
        *,
        project_id: UUID | None = None,
        status: GenerativeDesignRunStatus | None = None,
        limit: int = 100,
        offset: int = 0,
    ) -> Sequence[GenerativeDesignRun]:
        """
        List generative design runs.
        """

        if limit < 1:
            raise ValueError(
                "limit must be greater than zero."
            )

        if offset < 0:
            raise ValueError(
                "offset cannot be negative."
            )

        statement = select(
            GenerativeDesignRun
        )

        if project_id is not None:
            statement = statement.where(
                GenerativeDesignRun.project_id
                == project_id
            )

        if status is not None:
            statement = statement.where(
                GenerativeDesignRun.status
                == status
            )

        statement = (
            statement
            .order_by(
                GenerativeDesignRun.created_at.desc()
            )
            .offset(offset)
            .limit(limit)
        )

        result = await self.session.execute(
            statement
        )

        return result.scalars().all()

    async def update_run(
        self,
        run_id: UUID,
        *,
        name: str | None = None,
        status: GenerativeDesignRunStatus | None = None,
        constraints: dict[str, Any] | None = None,
        candidate_count: int | None = None,
        completed_at: datetime | None = None,
        error_message: str | None = None,
        updated_by: str | None = None,
    ) -> GenerativeDesignRun | None:
        """
        Update an existing run.

        Only explicitly supplied values are modified.
        """

        run = await self.get_run(
            run_id
        )

        if run is None:
            return None

        if name is not None:
            run.name = name

        if status is not None:
            run.status = status

        if constraints is not None:
            run.constraints = constraints

        if candidate_count is not None:
            if candidate_count < 0:
                raise ValueError(
                    "candidate_count cannot be negative."
                )

            run.candidate_count = candidate_count

        if completed_at is not None:
            run.completed_at = completed_at

        if error_message is not None:
            run.error_message = error_message

        if updated_by is not None:
            run.updated_by = updated_by

        await self.session.flush()

        return run

    async def delete_run(
        self,
        run_id: UUID,
    ) -> bool:
        """
        Delete a run.

        Candidate rows are removed through the configured
        database/model cascade on run deletion.
        """

        run = await self.get_run(
            run_id
        )

        if run is None:
            return False

        await self.session.delete(
            run
        )

        await self.session.flush()

        return True

    # ==================================================================
    # CANDIDATES
    # ==================================================================

    async def create_candidate(
        self,
        *,
        run_id: UUID,
        name: str,
        geometry: dict[str, Any],
        metrics: dict[str, Any],
        evaluation: dict[str, Any],
        score: float,
        rank: int | None = None,
        status: DesignCandidateStatus | None = None,
        created_by: str | None = None,
    ) -> DesignCandidateRecord:
        """
        Create one generated design candidate.
        """

        values: dict[str, Any] = {
            "run_id": run_id,
            "name": name,
            "geometry": geometry,
            "metrics": metrics,
            "evaluation": evaluation,
            "score": score,
            "rank": rank,
            "created_by": created_by,
        }

        if status is not None:
            values["status"] = status

        candidate = DesignCandidateRecord(
            **values
        )

        self.session.add(
            candidate
        )

        await self.session.flush()

        return candidate

    async def create_candidates(
        self,
        *,
        run_id: UUID,
        candidates: Sequence[
            dict[str, Any]
        ],
        created_by: str | None = None,
    ) -> list[DesignCandidateRecord]:
        """
        Persist an entire generated candidate population.

        All records remain inside the current transaction.
        """

        if not candidates:
            return []

        records: list[
            DesignCandidateRecord
        ] = []

        for data in candidates:
            values: dict[str, Any] = {
                "run_id": run_id,
                "name": data["name"],
                "geometry": data.get(
                    "geometry",
                    {},
                ),
                "metrics": data.get(
                    "metrics",
                    {},
                ),
                "evaluation": data.get(
                    "evaluation",
                    {},
                ),
                "score": float(
                    data.get(
                        "score",
                        0.0,
                    )
                ),
                "rank": data.get(
                    "rank"
                ),
                "created_by": created_by,
            }

            candidate_status = data.get(
                "status"
            )

            if candidate_status is not None:
                values["status"] = (
                    candidate_status
                )

            record = DesignCandidateRecord(
                **values
            )

            self.session.add(
                record
            )

            records.append(
                record
            )

        await self.session.flush()

        return records

    async def get_candidate(
        self,
        candidate_id: UUID,
    ) -> DesignCandidateRecord | None:
        """
        Retrieve a candidate by UUID.
        """

        statement = (
            select(
                DesignCandidateRecord
            )
            .where(
                DesignCandidateRecord.id
                == candidate_id
            )
        )

        result = await self.session.execute(
            statement
        )

        return result.scalar_one_or_none()

    async def list_candidates(
        self,
        *,
        run_id: UUID | None = None,
        status: DesignCandidateStatus | None = None,
        limit: int = 100,
        offset: int = 0,
    ) -> Sequence[DesignCandidateRecord]:
        """
        List candidates belonging to a run.
        """

        if limit < 1:
            raise ValueError(
                "limit must be greater than zero."
            )

        if offset < 0:
            raise ValueError(
                "offset cannot be negative."
            )

        statement = select(
            DesignCandidateRecord
        )

        if run_id is not None:
            statement = statement.where(
                DesignCandidateRecord.run_id
                == run_id
            )

        if status is not None:
            statement = statement.where(
                DesignCandidateRecord.status
                == status
            )

        statement = (
            statement
            .order_by(
                DesignCandidateRecord.rank.asc().nullslast(),
                DesignCandidateRecord.score.desc(),
            )
            .offset(offset)
            .limit(limit)
        )

        result = await self.session.execute(
            statement
        )

        return result.scalars().all()

    async def update_candidate(
        self,
        candidate_id: UUID,
        *,
        name: str | None = None,
        geometry: dict[str, Any] | None = None,
        metrics: dict[str, Any] | None = None,
        evaluation: dict[str, Any] | None = None,
        score: float | None = None,
        rank: int | None = None,
        status: DesignCandidateStatus | None = None,
        updated_by: str | None = None,
    ) -> DesignCandidateRecord | None:
        """
        Update a candidate.
        """

        candidate = await self.get_candidate(
            candidate_id
        )

        if candidate is None:
            return None

        if name is not None:
            candidate.name = name

        if geometry is not None:
            candidate.geometry = geometry

        if metrics is not None:
            candidate.metrics = metrics

        if evaluation is not None:
            candidate.evaluation = evaluation

        if score is not None:
            candidate.score = score

        if rank is not None:
            if rank < 1:
                raise ValueError(
                    "rank must be greater than zero."
                )

            candidate.rank = rank

        if status is not None:
            candidate.status = status

        if updated_by is not None:
            candidate.updated_by = updated_by

        await self.session.flush()

        return candidate

    async def delete_candidate(
        self,
        candidate_id: UUID,
    ) -> bool:
        """
        Delete one candidate.
        """

        candidate = await self.get_candidate(
            candidate_id
        )

        if candidate is None:
            return False

        await self.session.delete(
            candidate
        )

        await self.session.flush()

        return True

    async def delete_candidates_for_run(
        self,
        run_id: UUID,
    ) -> int:
        """
        Delete all candidates belonging to a run.

        This is useful when replacing an existing candidate
        population within the same transaction.
        """

        statement = (
            select(
                DesignCandidateRecord
            )
            .where(
                DesignCandidateRecord.run_id
                == run_id
            )
        )

        result = await self.session.execute(
            statement
        )

        candidates = result.scalars().all()

        for candidate in candidates:
            await self.session.delete(
                candidate
            )

        if candidates:
            await self.session.flush()

        return len(candidates)

    # ==================================================================
    # COUNTS
    # ==================================================================

    async def count_candidates(
        self,
        run_id: UUID,
    ) -> int:
        """
        Return the actual number of candidates belonging to a run.
        """

        statement = select(
            func.count(
                DesignCandidateRecord.id
            )
        ).where(
            DesignCandidateRecord.run_id
            == run_id
        )

        result = await self.session.execute(
            statement
        )

        return int(
            result.scalar_one()
        )

    async def update_run_candidate_count(
        self,
        run_id: UUID,
    ) -> GenerativeDesignRun | None:
        """
        Synchronize the run's candidate_count with
        the actual persisted candidate rows.
        """

        run = await self.get_run(
            run_id
        )

        if run is None:
            return None

        count = await self.count_candidates(
            run_id
        )

        run.candidate_count = count

        await self.session.flush()

        return run

    # ==================================================================
    # RANKING
    # ==================================================================

    async def get_best_candidate(
        self,
        run_id: UUID,
    ) -> DesignCandidateRecord | None:
        """
        Return the highest-ranked candidate.

        Rank is preferred when available, with score as the
        secondary ordering criterion.
        """

        statement = (
            select(
                DesignCandidateRecord
            )
            .where(
                DesignCandidateRecord.run_id
                == run_id
            )
            .order_by(
                DesignCandidateRecord.rank.asc().nullslast(),
                DesignCandidateRecord.score.desc(),
            )
            .limit(1)
        )

        result = await self.session.execute(
            statement
        )

        return result.scalar_one_or_none()

    async def get_top_candidates(
        self,
        run_id: UUID,
        *,
        limit: int = 10,
    ) -> Sequence[DesignCandidateRecord]:
        """
        Return the top-ranked candidates.
        """

        if limit < 1:
            raise ValueError(
                "limit must be greater than zero."
            )

        statement = (
            select(
                DesignCandidateRecord
            )
            .where(
                DesignCandidateRecord.run_id
                == run_id
            )
            .order_by(
                DesignCandidateRecord.rank.asc().nullslast(),
                DesignCandidateRecord.score.desc(),
            )
            .limit(limit)
        )

        result = await self.session.execute(
            statement
        )

        return result.scalars().all()

    # ==================================================================
    # TRANSACTION CONTROL
    # ==================================================================

    async def flush(self) -> None:
        """
        Flush pending changes without committing.

        The service layer decides whether the transaction is
        ultimately committed or rolled back.
        """

        await self.session.flush()
