"""
IMAGINE
Generative Design UI

Streamlit presentation layer for constraint-driven
architectural generative design.

Responsibilities
----------------
- Project selection
- Constraint summary
- Design generation
- Generation progress
- Error handling
- Ranked candidate presentation
- Best-design selection
- Run history
- Regeneration
- Candidate inspection

The UI does NOT:
- generate designs directly
- calculate scores directly
- manipulate database transactions directly
- commit or rollback database transactions

Those responsibilities belong to the service/repository layers.
"""

from __future__ import annotations

import asyncio
import inspect
import threading
from datetime import datetime
from typing import Any
from uuid import UUID

import pandas as pd
import streamlit as st
from sqlalchemy import select

from database.connection import AsyncSessionLocal
from projects.projects.model import Project

from architecture.generative_design.models import (
    DesignCandidateRecord,
    GenerativeDesignRun,
)
from architecture.generative_design.repository import (
    GenerativeDesignRepository,
)
from architecture.generative_design.service import (
    GenerativeDesignService,
)


# ============================================================================
# CONSTANTS
# ============================================================================

MODULE_TITLE = "Generative Design"

RUN_STATUS_PENDING = "pending"
RUN_STATUS_RUNNING = "running"
RUN_STATUS_COMPLETED = "completed"
RUN_STATUS_FAILED = "failed"

CANDIDATE_STATUS_GENERATED = "generated"


# ============================================================================
# ASYNC-SAFE EXECUTION
# ============================================================================

def _run_async(
    coroutine_factory: Any,
) -> Any:
    """
    Execute an async operation safely from Streamlit.

    Streamlit normally executes synchronously, but an existing
    event loop may exist in some environments.

    Instead of calling asyncio.run() directly on the Streamlit
    execution thread, this function executes the coroutine inside
    a dedicated worker thread with its own event loop.

    Parameters
    ----------
    coroutine_factory:
        Callable returning an awaitable.

    Returns
    -------
    Any
        Result returned by the coroutine.

    Raises
    ------
    BaseException
        Re-raises the exception generated by the worker coroutine.
    """

    result: dict[str, Any] = {}
    error: dict[str, BaseException] = {}

    def runner() -> None:
        try:
            result["value"] = asyncio.run(
                coroutine_factory()
            )
        except BaseException as exc:
            error["exception"] = exc

    thread = threading.Thread(
        target=runner,
        daemon=True,
    )

    thread.start()
    thread.join()

    if "exception" in error:
        raise error["exception"]

    return result.get("value")


# ============================================================================
# SESSION STATE
# ============================================================================

def _initialize_state() -> None:
    """
    Initialize Generative Design UI state.
    """

    defaults: dict[str, Any] = {
        "gd_project_id": None,
        "gd_project_name": None,
        "gd_selected_run_id": None,
        "gd_selected_candidate_id": None,
        "gd_best_candidate_id": None,
        "gd_last_generation": None,
        "gd_generation_error": None,
        "gd_show_run_history": False,
        "gd_generation_requested": False,
    }

    for key, value in defaults.items():
        if key not in st.session_state:
            st.session_state[key] = value


# ============================================================================
# DATABASE HELPERS
# ============================================================================

async def _load_projects() -> list[Project]:
    """
    Load available projects asynchronously.
    """

    async with AsyncSessionLocal() as session:

        statement = (
            select(Project)
            .order_by(
                Project.name.asc()
            )
        )

        result = await session.execute(
            statement
        )

        return list(
            result.scalars().all()
        )


async def _load_run(
    run_id: UUID,
) -> GenerativeDesignRun | None:
    """
    Load one generation run with candidates.
    """

    async with AsyncSessionLocal() as session:

        repository = GenerativeDesignRepository(
            session
        )

        return await repository.get_run_with_candidates(
            run_id
        )


async def _load_runs(
    project_id: UUID,
) -> list[GenerativeDesignRun]:
    """
    Load generation history for a project.
    """

    async with AsyncSessionLocal() as session:

        repository = GenerativeDesignRepository(
            session
        )

        runs = await repository.list_runs(
            project_id=project_id,
            limit=100,
        )

        return list(runs)


async def _load_candidate(
    candidate_id: UUID,
) -> DesignCandidateRecord | None:
    """
    Load one candidate.
    """

    async with AsyncSessionLocal() as session:

        repository = GenerativeDesignRepository(
            session
        )

        return await repository.get_candidate(
            candidate_id
        )


# ============================================================================
# SERVICE HELPERS
# ============================================================================

def _build_service(
    session: Any,
) -> GenerativeDesignService:
    """
    Construct the GenerativeDesignService.

    The current architecture uses AsyncSession as the service
    dependency.

    If the service exposes a different constructor signature,
    this helper keeps construction isolated to one location.
    """

    try:
        return GenerativeDesignService(
            session
        )
    except TypeError:

        repository = GenerativeDesignRepository(
            session
        )

        return GenerativeDesignService(
            session=session,
            repository=repository,
        )


async def _generate_designs(
    project_id: UUID,
    parameters: dict[str, Any],
) -> Any:
    """
    Execute GenerativeDesignService.generate().

    The service owns:
        - constraint loading
        - validation
        - generation
        - scoring
        - candidate persistence
        - candidate_count update
        - completion/failure state
        - transaction commit/rollback
    """

    async with AsyncSessionLocal() as session:

        service = _build_service(
            session
        )

        generate_method = getattr(
            service,
            "generate",
            None,
        )

        if generate_method is None:
            raise AttributeError(
                "GenerativeDesignService.generate() "
                "does not exist."
            )

        signature = inspect.signature(
            generate_method
        )

        kwargs: dict[str, Any] = {}

        parameters_available = signature.parameters

        if "project_id" in parameters_available:
            kwargs["project_id"] = project_id

        if "parameters" in parameters_available:
            kwargs["parameters"] = parameters

        elif "options" in parameters_available:
            kwargs["options"] = parameters

        elif "generation_parameters" in parameters_available:
            kwargs[
                "generation_parameters"
            ] = parameters

        elif "settings" in parameters_available:
            kwargs["settings"] = parameters

        # If generate() expects only positional arguments,
        # support the common project_id / parameters contract.
        if kwargs:
            return await generate_method(
                **kwargs
            )

        return await generate_method(
            project_id,
            parameters,
        )


# ============================================================================
# NORMALIZATION HELPERS
# ============================================================================

def _object_id(
    value: Any,
) -> UUID | None:
    """
    Extract a UUID from an ORM object or UUID value.
    """

    if value is None:
        return None

    if isinstance(value, UUID):
        return value

    object_id = getattr(
        value,
        "id",
        None,
    )

    if object_id is None:
        return None

    if isinstance(object_id, UUID):
        return object_id

    try:
        return UUID(
            str(object_id)
        )
    except (TypeError, ValueError):
        return None


def _as_dict(
    value: Any,
) -> dict[str, Any]:
    """
    Safely normalize JSON-like values for UI display.
    """

    if value is None:
        return {}

    if isinstance(value, dict):
        return value

    try:
        return dict(value)
    except (TypeError, ValueError):
        return {
            "value": value
        }


def _format_datetime(
    value: Any,
) -> str:
    """
    Format datetime values for the UI.
    """

    if value is None:
        return "—"

    if isinstance(
        value,
        datetime,
    ):
        return value.strftime(
            "%Y-%m-%d %H:%M"
        )

    return str(value)


def _run_status_icon(
    status: str | None,
) -> str:
    """
    Return a visual status icon.
    """

    icons = {
        RUN_STATUS_PENDING: "⏳",
        RUN_STATUS_RUNNING: "⚙️",
        RUN_STATUS_COMPLETED: "✅",
        RUN_STATUS_FAILED: "❌",
    }

    return icons.get(
        status or "",
        "•",
    )


# ============================================================================
# PROJECT SELECTOR
# ============================================================================

def _render_project_selector(
    projects: list[Project],
) -> Project | None:
    """
    Render project selection.
    """

    if not projects:
        st.warning(
            "No projects are available. "
            "Create a project before running Generative Design."
        )

        return None

    project_options = {
        str(project.id): project
        for project in projects
    }

    current_project_id = (
        st.session_state.gd_project_id
    )

    option_ids = list(
        project_options.keys()
    )

    default_index = 0

    if current_project_id is not None:

        current_key = str(
            current_project_id
        )

        if current_key in option_ids:
            default_index = option_ids.index(
                current_key
            )

    selected_key = st.selectbox(
        "Project",
        options=option_ids,
        index=default_index,
        format_func=lambda value: (
            project_options[value].name
        ),
        key="gd_project_selector",
    )

    selected_project = project_options[
        selected_key
    ]

    selected_id = _object_id(
        selected_project
    )

    if selected_id is not None:

        if (
            st.session_state.gd_project_id
            != selected_id
        ):
            st.session_state.gd_project_id = (
                selected_id
            )

            st.session_state.gd_project_name = (
                selected_project.name
            )

            st.session_state.gd_selected_run_id = None
            st.session_state.gd_selected_candidate_id = None
            st.session_state.gd_best_candidate_id = None

    return selected_project


# ============================================================================
# CONSTRAINT SUMMARY
# ============================================================================

def _render_constraint_summary(
    project: Project,
) -> None:
    """
    Display the constraint sources used by Generative Design.

    Actual normalized constraints are supplied by the service layer.
    """

    st.subheader(
        "Design Constraints"
    )

    st.caption(
        "Generative Design consumes constraints from the upstream "
        "architecture modules instead of using fixed design placeholders."
    )

    constraint_columns = st.columns(5)

    modules = [
        (
            "📐",
            "Zoning",
        ),
        (
            "🗺️",
            "Site Planning",
        ),
        (
            "🏢",
            "Floor Planning",
        ),
        (
            "🚪",
            "Room Programming",
        ),
        (
            "✅",
            "Compliance",
        ),
    ]

    for column, (
        icon,
        label,
    ) in zip(
        constraint_columns,
        modules,
    ):
        with column:
            st.metric(
                label,
                f"{icon} Connected",
            )

    st.info(
        f"Project: **{project.name}**  \n"
        "The generation service will normalize and validate "
        "the project's current architectural constraints before "
        "creating design candidates."
    )


# ============================================================================
# GENERATION PARAMETERS
# ============================================================================

def _render_generation_parameters() -> dict[str, Any]:
    """
    Render generation controls.

    These parameters are intentionally generic. The service/generator
    remains responsible for interpreting them.
    """

    st.subheader(
        "Generation Parameters"
    )

    col1, col2, col3 = st.columns(3)

    with col1:

        candidate_count = st.number_input(
            "Candidate count",
            min_value=1,
            max_value=500,
            value=20,
            step=1,
            key="gd_candidate_count",
        )

    with col2:

        diversity = st.slider(
            "Design diversity",
            min_value=0.0,
            max_value=1.0,
            value=0.70,
            step=0.05,
            key="gd_diversity",
        )

    with col3:

        ranking_strategy = st.selectbox(
            "Ranking strategy",
            options=[
                "balanced",
                "compliance_first",
                "space_efficiency",
                "cost_efficiency",
            ],
            index=0,
            key="gd_ranking_strategy",
        )

    return {
        "candidate_count": int(
            candidate_count
        ),
        "diversity": float(
            diversity
        ),
        "ranking_strategy": ranking_strategy,
    }


# ============================================================================
# GENERATION
# ============================================================================

def _render_generation_controls(
    project: Project,
    parameters: dict[str, Any],
) -> None:
    """
    Render generation and regeneration actions.
    """

    st.subheader(
        "Generate Design Options"
    )

    generate_col, history_col = st.columns(
        [2, 1]
    )

    with generate_col:

        generate = st.button(
            "✨ Generate Design Options",
            type="primary",
            use_container_width=True,
            key="gd_generate_button",
        )

    with history_col:

        history = st.button(
            "📜 Run History",
            use_container_width=True,
            key="gd_history_button",
        )

    if history:
        st.session_state.gd_show_run_history = (
            not st.session_state.gd_show_run_history
        )

    if not generate:
        return

    project_id = _object_id(
        project
    )

    if project_id is None:
        st.error(
            "The selected project does not have a valid UUID."
        )
        return

    st.session_state.gd_generation_error = None
    st.session_state.gd_last_generation = None
    st.session_state.gd_generation_requested = True

    progress = st.progress(
        0,
        text="Preparing generative design run...",
    )

    status_box = st.empty()

    try:

        progress.progress(
            10,
            text="Loading project constraints...",
        )

        status_box.info(
            "Collecting Zoning, Site Planning, Floor Planning, "
            "Room Programming and Compliance constraints."
        )

        progress.progress(
            30,
            text="Generating candidate designs...",
        )

        result = _run_async(
            lambda: _generate_designs(
                project_id,
                parameters,
            )
        )

        progress.progress(
            80,
            text="Persisting and ranking candidates...",
        )

        st.session_state.gd_last_generation = (
            result
        )

        progress.progress(
            100,
            text="Generation completed.",
        )

        status_box.success(
            "Generative design run completed successfully."
        )

        run_id = _extract_run_id(
            result
        )

        if run_id is not None:
            st.session_state.gd_selected_run_id = (
                run_id
            )

        st.rerun()

    except Exception as exc:

        progress.progress(
            100,
            text="Generation failed.",
        )

        st.session_state.gd_generation_error = (
            str(exc)
        )

        status_box.error(
            "Generative design generation failed."
        )

        st.exception(exc)


# ============================================================================
# RESULT EXTRACTION
# ============================================================================

def _extract_run_id(
    result: Any,
) -> UUID | None:
    """
    Extract the generated run UUID from common service return forms.
    """

    if result is None:
        return None

    if isinstance(
        result,
        UUID,
    ):
        return result

    if isinstance(
        result,
        dict,
    ):

        for key in (
            "run_id",
            "id",
        ):

            if key in result:
                return _object_id(
                    result[key]
                )

    return _object_id(
        result
    )


# ============================================================================
# RUN HISTORY
# ============================================================================

def _render_run_history(
    project: Project,
) -> None:
    """
    Render generation run history.
    """

    if not st.session_state.gd_show_run_history:
        return

    project_id = _object_id(
        project
    )

    if project_id is None:
        return

    st.divider()

    st.subheader(
        "Generation Run History"
    )

    try:

        runs = _run_async(
            lambda: _load_runs(
                project_id
            )
        )

    except Exception as exc:

        st.error(
            "Unable to load generation history."
        )

        st.exception(exc)

        return

    if not runs:

        st.info(
            "No generative design runs exist for this project yet."
        )

        return

    rows = []

    for run in runs:

        rows.append(
            {
                "Run": str(run.id),
                "Status": (
                    f"{_run_status_icon(run.status)} "
                    f"{run.status}"
                ),
                "Candidates": run.candidate_count,
                "Created": _format_datetime(
                    run.created_at
                ),
                "Completed": _format_datetime(
                    run.completed_at
                ),
            }
        )

    history_df = pd.DataFrame(
        rows
    )

    st.dataframe(
        history_df,
        use_container_width=True,
        hide_index=True,
    )

    run_ids = [
        str(run.id)
        for run in runs
    ]

    selected_history_run = st.selectbox(
        "Inspect run",
        options=run_ids,
        format_func=lambda value: (
            next(
                (
                    f"{value} · "
                    f"{next_run.status} · "
                    f"{next_run.candidate_count} candidates"
                    for next_run in runs
                    if str(next_run.id) == value
                ),
                value,
            )
        ),
        key="gd_history_run_selector",
    )

    if selected_history_run:

        try:

            selected_run = _run_async(
                lambda: _load_run(
                    UUID(
                        selected_history_run
                    )
                )
            )

            if selected_run is not None:

                st.session_state.gd_selected_run_id = (
                    selected_run.id
                )

                _render_run_summary(
                    selected_run
                )

                _render_candidates(
                    selected_run
                )

        except Exception as exc:

            st.error(
                "Unable to load the selected run."
            )

            st.exception(exc)


# ============================================================================
# RUN SUMMARY
# ============================================================================

def _render_run_summary(
    run: GenerativeDesignRun,
) -> None:
    """
    Display summary information for a generation run.
    """

    st.subheader(
        "Generation Run"
    )

    col1, col2, col3, col4 = st.columns(
        4
    )

    with col1:

        st.metric(
            "Status",
            f"{_run_status_icon(run.status)} "
            f"{run.status}",
        )

    with col2:

        st.metric(
            "Candidates",
            run.candidate_count,
        )

    with col3:

        st.metric(
            "Created",
            _format_datetime(
                run.created_at
            ),
        )

    with col4:

        st.metric(
            "Completed",
            _format_datetime(
                run.completed_at
            ),
        )

    if run.error_message:

        st.error(
            run.error_message
        )

    with st.expander(
        "Normalized Constraints",
        expanded=False,
    ):

        st.json(
            _as_dict(
                run.constraints
            )
        )


# ============================================================================
# CANDIDATE CARDS
# ============================================================================

def _render_candidates(
    run: GenerativeDesignRun,
) -> None:
    """
    Render ranked candidate cards.
    """

    candidates = list(
        run.candidates or []
    )

    st.subheader(
        "Ranked Design Candidates"
    )

    if not candidates:

        st.info(
            "This run has no persisted design candidates."
        )

        return

    candidates.sort(
        key=lambda candidate: (
            candidate.rank
            if candidate.rank is not None
            else 999999,
            -float(
                candidate.score or 0.0
            ),
        )
    )

    # ---------------------------------------------------------------
    # Determine current best candidate.
    # ---------------------------------------------------------------

    best_candidate = candidates[0]

    if (
        st.session_state.gd_best_candidate_id
        is None
        or not any(
            candidate.id
            == st.session_state.gd_best_candidate_id
            for candidate in candidates
        )
    ):

        st.session_state.gd_best_candidate_id = (
            best_candidate.id
        )

    # ---------------------------------------------------------------
    # Best design
    # ---------------------------------------------------------------

    st.markdown(
        "### 🏆 Best Design"
    )

    _render_candidate_card(
        best_candidate,
        featured=True,
    )

    st.divider()

    # ---------------------------------------------------------------
    # Candidate grid
    # ---------------------------------------------------------------

    columns = st.columns(
        3
    )

    for index, candidate in enumerate(
        candidates
    ):

        with columns[
            index % 3
        ]:

            _render_candidate_card(
                candidate,
                featured=False,
            )


# ============================================================================
# CANDIDATE CARD
# ============================================================================

def _render_candidate_card(
    candidate: DesignCandidateRecord,
    *,
    featured: bool,
) -> None:
    """
    Render one candidate.
    """

    candidate_id = _object_id(
        candidate
    )

    if candidate_id is None:
        return

    rank = (
        candidate.rank
        if candidate.rank is not None
        else "—"
    )

    score = float(
        candidate.score or 0.0
    )

    if featured:

        st.success(
            f"**#{rank} · {candidate.name}**"
        )

        st.metric(
            "Overall Score",
            f"{score:.3f}",
        )

    else:

        with st.container(
            border=True
        ):

            st.markdown(
                f"### #{rank} {candidate.name}"
            )

            st.caption(
                f"Status: {candidate.status}"
            )

            st.metric(
                "Score",
                f"{score:.3f}",
            )

            metrics = _as_dict(
                candidate.metrics
            )

            if metrics:

                metric_items = list(
                    metrics.items()
                )[:4]

                metric_columns = st.columns(
                    min(
                        len(metric_items),
                        2,
                    )
                )

                for column, (
                    key,
                    value,
                ) in zip(
                    metric_columns,
                    metric_items,
                ):

                    with column:

                        st.caption(
                            str(key)
                        )

                        st.write(
                            str(value)
                        )

            if st.button(
                "Inspect",
                key=(
                    f"gd_inspect_"
                    f"{candidate_id}"
                ),
                use_container_width=True,
            ):

                st.session_state.gd_selected_candidate_id = (
                    candidate_id
                )

                st.rerun()

    # ---------------------------------------------------------------
    # Featured selection
    # ---------------------------------------------------------------

    if featured:

        is_selected = (
            st.session_state.gd_best_candidate_id
            == candidate_id
        )

        if st.button(
            (
                "✓ Selected as Best Design"
                if is_selected
                else "Select as Best Design"
            ),
            key=(
                f"gd_best_"
                f"{candidate_id}"
            ),
            use_container_width=True,
        ):

            st.session_state.gd_best_candidate_id = (
                candidate_id
            )

            st.rerun()


# ============================================================================
# CANDIDATE INSPECTION
# ============================================================================

def _render_candidate_inspection() -> None:
    """
    Render detailed candidate inspection panel.
    """

    candidate_id = (
        st.session_state.gd_selected_candidate_id
    )

    if candidate_id is None:
        return

    try:

        candidate = _run_async(
            lambda: _load_candidate(
                candidate_id
            )
        )

    except Exception as exc:

        st.error(
            "Unable to load candidate."
        )

        st.exception(exc)

        return

    if candidate is None:

        st.warning(
            "The selected candidate no longer exists."
        )

        st.session_state.gd_selected_candidate_id = None

        return

    st.divider()

    st.subheader(
        f"🔍 Candidate Inspection · {candidate.name}"
    )

    close_col, _ = st.columns(
        [1, 5]
    )

    with close_col:

        if st.button(
            "Close",
            key="gd_close_candidate",
        ):

            st.session_state.gd_selected_candidate_id = None

            st.rerun()

    col1, col2, col3, col4 = st.columns(
        4
    )

    with col1:

        st.metric(
            "Rank",
            candidate.rank
            if candidate.rank is not None
            else "—",
        )

    with col2:

        st.metric(
            "Score",
            f"{float(candidate.score or 0.0):.3f}",
        )

    with col3:

        st.metric(
            "Status",
            candidate.status,
        )

    with col4:

        st.metric(
            "Candidate ID",
            str(candidate.id)[:8],
        )

    geometry_tab, metrics_tab, evaluation_tab = st.tabs(
        [
            "Geometry",
            "Metrics",
            "Evaluation",
        ]
    )

    with geometry_tab:

        st.json(
            _as_dict(
                candidate.geometry
            )
        )

    with metrics_tab:

        st.json(
            _as_dict(
                candidate.metrics
            )
        )

    with evaluation_tab:

        st.json(
            _as_dict(
                candidate.evaluation
            )
        )


# ============================================================================
# REGENERATION
# ============================================================================

def _render_regeneration(
    project: Project,
) -> None:
    """
    Render regeneration controls.

    Regeneration delegates completely to the existing service layer.
    """

    st.divider()

    st.subheader(
        "Regenerate"
    )

    st.caption(
        "Generate a new candidate population using the project's "
        "current constraints."
    )

    project_id = _object_id(
        project
    )

    if project_id is None:
        return

    col1, col2 = st.columns(
        2
    )

    with col1:

        regenerate_count = st.number_input(
            "New candidate count",
            min_value=1,
            max_value=500,
            value=20,
            step=1,
            key="gd_regenerate_count",
        )

    with col2:

        regenerate_diversity = st.slider(
            "New diversity",
            min_value=0.0,
            max_value=1.0,
            value=0.80,
            step=0.05,
            key="gd_regenerate_diversity",
        )

    if st.button(
        "🔄 Regenerate Designs",
        use_container_width=True,
        key="gd_regenerate_button",
    ):

        parameters = {
            "candidate_count": int(
                regenerate_count
            ),
            "diversity": float(
                regenerate_diversity
            ),
            "ranking_strategy": "balanced",
            "regeneration": True,
        }

        st.session_state.gd_generation_error = None

        progress = st.progress(
            0,
            text="Preparing regeneration...",
        )

        status = st.empty()

        try:

            progress.progress(
                20,
                text="Loading current constraints...",
            )

            status.info(
                "Regenerating from the current project constraints."
            )

            progress.progress(
                50,
                text="Generating new design population...",
            )

            result = _run_async(
                lambda: _generate_designs(
                    project_id,
                    parameters,
                )
            )

            progress.progress(
                85,
                text="Persisting and ranking regenerated candidates...",
            )

            run_id = _extract_run_id(
                result
            )

            if run_id is not None:

                st.session_state.gd_selected_run_id = (
                    run_id
                )

            progress.progress(
                100,
                text="Regeneration completed.",
            )

            status.success(
                "New design candidates generated successfully."
            )

            st.rerun()

        except Exception as exc:

            progress.progress(
                100,
                text="Regeneration failed.",
            )

            st.session_state.gd_generation_error = (
                str(exc)
            )

            status.error(
                "Regeneration failed."
            )

            st.exception(exc)


# ============================================================================
# ERROR STATE
# ============================================================================

def _render_error_state() -> None:
    """
    Display the most recent generation error.
    """

    error = (
        st.session_state.gd_generation_error
    )

    if not error:
        return

    st.error(
        "Generative Design Error"
    )

    st.code(
        str(error)
    )

    if st.button(
        "Clear Error",
        key="gd_clear_error",
    ):

        st.session_state.gd_generation_error = None

        st.rerun()


# ============================================================================
# MAIN UI
# ============================================================================

def render_generative_design() -> None:
    """
    Render the complete Generative Design interface.

    This is the function imported by streamlit_app.py:

        from architecture.generative_design.ui import (
            render_generative_design,
        )

    and called with:

        render_generative_design()
    """

    _initialize_state()

    # ------------------------------------------------------------------
    # Header
    # ------------------------------------------------------------------

    st.title(
        "✨ Generative Design"
    )

    st.caption(
        "Constraint-driven architectural design generation, "
        "evaluation and ranking."
    )

    # ------------------------------------------------------------------
    # Project loading
    # ------------------------------------------------------------------

    try:

        projects = _run_async(
            _load_projects
        )

    except Exception as exc:

        st.error(
            "Unable to load projects."
        )

        st.exception(exc)

        return

    # ------------------------------------------------------------------
    # Project selection
    # ------------------------------------------------------------------

    project = _render_project_selector(
        projects
    )

    if project is None:
        return

    # ------------------------------------------------------------------
    # Project summary
    # ------------------------------------------------------------------

    st.markdown(
        f"## 📁 {project.name}"
    )

    if project.description:

        st.caption(
            project.description
        )

    # ------------------------------------------------------------------
    # Constraint summary
    # ------------------------------------------------------------------

    _render_constraint_summary(
        project
    )

    st.divider()

    # ------------------------------------------------------------------
    # Generation parameters
    # ------------------------------------------------------------------

    parameters = _render_generation_parameters()

    st.divider()

    # ------------------------------------------------------------------
    # Generation controls
    # ------------------------------------------------------------------

    _render_generation_controls(
        project,
        parameters,
    )

    # ------------------------------------------------------------------
    # Error state
    # ------------------------------------------------------------------

    _render_error_state()

    # ------------------------------------------------------------------
    # Last/current run
    # ------------------------------------------------------------------

    selected_run_id = (
        st.session_state.gd_selected_run_id
    )

    if selected_run_id is not None:

        try:

            current_run = _run_async(
                lambda: _load_run(
                    selected_run_id
                )
            )

        except Exception as exc:

            st.error(
                "Unable to load the generation run."
            )

            st.exception(exc)

            current_run = None

        if current_run is not None:

            _render_run_summary(
                current_run
            )

            _render_candidates(
                current_run
            )

    # ------------------------------------------------------------------
    # Candidate inspection
    # ------------------------------------------------------------------

    _render_candidate_inspection()

    # ------------------------------------------------------------------
    # Regeneration
    # ------------------------------------------------------------------

    _render_regeneration(
        project
    )

    # ------------------------------------------------------------------
    # Run history
    # ------------------------------------------------------------------

    _render_run_history(
        project
        )
